starting with cluster address: emqx.dtwins:18083
cluster user set to: my-app and cluster password set to: AAA4A275-BEEC-4AF8-B70B-DAAC0341F8EB
kubernetes api address set to: someaddress:6443
max queue set to: -1 and max inflight set to: 16
date: 2024-12-11 18:46:09.039419 | Queue: total=0, avg=0.00, max=-1 | Inflight: total=0, avg=0.00, max=16
Returning scale = True (queue threshold exceeded)
Traceback (most recent call last):
  File "/code/main.py", line 46, in <module>
    main()
    ~~~~^^
  File "/code/main.py", line 38, in main
    scale_cluster(kube_client)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/code/scale_logic.py", line 32, in scale_cluster
    emqx_body = kube_client.read_namespaced_stateful_set(name, namespace)
  File "/usr/local/lib/python3.13/site-packages/kubernetes/client/api/apps_v1_api.py", line 7298, in read_namespaced_stateful_set
    return self.read_namespaced_stateful_set_with_http_info(name, namespace, **kwargs)  # noqa: E501
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/kubernetes/client/api/apps_v1_api.py", line 7385, in read_namespaced_stateful_set_with_http_info
    return self.api_client.call_api(
           ~~~~~~~~~~~~~~~~~~~~~~~~^
        '/apis/apps/v1/namespaces/{namespace}/statefulsets/{name}', 'GET',
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<11 lines>...
        _request_timeout=local_var_params.get('_request_timeout'),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        collection_formats=collection_formats)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
                           path_params, query_params, header_params,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
                           _return_http_data_only, collection_formats,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                           _preload_content, _request_timeout, _host)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
        method, url, query_params=query_params, headers=header_params,
        post_params=post_params, body=body,
        _preload_content=_preload_content,
        _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.13/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
           ~~~~~~~~~~~~~~~~~~~~^^^^^
                                query_params=query_params,
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                _preload_content=_preload_content,
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                _request_timeout=_request_timeout,
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                headers=headers)
                                ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/kubernetes/client/rest.py", line 244, in GET
    return self.request("GET", url,
           ~~~~~~~~~~~~^^^^^^^^^^^^
                        headers=headers,
                        ^^^^^^^^^^^^^^^^
                        _preload_content=_preload_content,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        _request_timeout=_request_timeout,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        query_params=query_params)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/kubernetes/client/rest.py", line 238, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'c2ee1009-14b1-4db4-83fb-539a2a0392ec', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': 'dae0a0b3-130b-4195-ab6f-aab96021abe2', 'X-Kubernetes-Pf-Prioritylevel-Uid': '0b99e977-d337-40c0-9e0a-8b360adfee8f', 'Date': 'Wed, 11 Dec 2024 18:46:09 GMT', 'Content-Length': '427'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"statefulsets.apps \"emqx\" is forbidden: User \"system:serviceaccount:dtwins:mqtt-manager\" cannot get resource \"statefulsets\" in API group \"apps\" in the namespace \"dtwins\": RBAC: clusterrole.rbac.authorization.k8s.io \"mqtt-manager\" not found","reason":"Forbidden","details":{"name":"emqx","group":"apps","kind":"statefulsets"},"code":403}


